CREATE TABLE IF NOT EXISTS sanctions
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type        VARCHAR(255),
    value       VARCHAR(255),
    description VARCHAR(1000)
    );

CREATE TABLE IF NOT EXISTS operators
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) UNIQUE,
    password VARCHAR(255)
    );

CREATE TABLE IF NOT EXISTS admins
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) UNIQUE,
    password VARCHAR(255)
    );

CREATE TABLE IF NOT EXISTS rules_engine_results
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_clear    BOOLEAN,
    sanction_id BIGINT,
    FOREIGN KEY (sanction_id) REFERENCES sanctions (id)
    );

CREATE TABLE IF NOT EXISTS operators_results
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_clear               BOOLEAN,
    comment                VARCHAR(1000),
    operator_id            BIGINT,
    rules_engine_result_id BIGINT,
    FOREIGN KEY (operator_id) REFERENCES operators (id),
    FOREIGN KEY (rules_engine_result_id) REFERENCES rules_engine_results (id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS transactions
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_from        VARCHAR(255),
    client_to          VARCHAR(255),
    amount             BIGINT,
    bank_from          VARCHAR(255),
    bank_to            VARCHAR(255),
    pay_system_from    VARCHAR(255),
    pay_system_to      VARCHAR(255),
    transfer_date      TIMESTAMP,
    country_from       VARCHAR(255),
    country_to         VARCHAR(255),
    operator_result_id BIGINT,
    FOREIGN KEY (operator_result_id) REFERENCES operators_results (id) ON DELETE CASCADE
    );
